apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: local-backstage
  annotations:
    github.com/project-slug: yogeehhegde/local-backstage
spec:
  type: other
  lifecycle: unknown
  owner: team-a
