apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: flex-iac
  namespace: local-flex
  description: Roles specific to the Flex Platform Capabilities IaC teams
spec:
  owner: flex-platform-iac
