apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: local-backstage
  namespace: local-flex
  labels:
    example.com/sox: "false"
    example.com/security: red
    example.com/tier: "1"
    example.com/hippa: "false"
    example.com/stateless: "true"
    example.com/envoy_enabled: "true"
    example.com/containerised: done
    example.com/greendot: todo
    example.com/multi_region: todo
    example.com/regional: todo
    example.com/otk: todo
    example.com/al22: todo
  annotations:
    github.com/project-slug: yogeehhegde/local-backstage
    kafka.apache.org/consumer-groups: 127.0.0.1:9092/console-consumer-4612
    backstage.io/kubernetes-label-selector: "namespace=otk-local"
    backstage.io/code-coverage: enabled
    backstage.io/techdocs-ref: url:https://github.com/yogeehhegde/local-backstage/tree/main
  links:
    - url: http://localhost:3000/catalog
      title: local backstage
      icon: dashboard    
spec:
  type: service
  lifecycle: experimental
  owner: flex-platform-iac
  system: flex-iac
  dependsOn:
    - resource:local-flex/central-kafka
    - resource:local-flex/flex-redis
  dependencyOf:
    - component:local-flex/flex-orchestrator
