apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flex-orchestrator
  namespace: local-flex
  annotations:
    github.com/project-slug: yogeehhegde/local-backstage
spec:
  type: service
  lifecycle: experimental
  owner: flex-platform-iac
  system: flex-iac
  dependsOn:
    - resource:local-flex/flex-dynamodb
