apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: central-kafka
  namespace: local-flex
  description: central kafka cluster
spec:
  type: cluster
  owner: flex-platform-iac
  system: flex-iac
