site_name: 'flex-platform-services-metadata'
repo_url: https://github.com/yogeehhegde/local-backstage
edit_uri: edit/main/docs

nav:
  - Home: index.md
  - SLO defination: index.md

plugins:
  - techdocs-core
